version: 2.1
jobs:
  build:
    docker:
      - image: dannydainton/htmlextra
    steps:
      - checkout
      - run:
         command: |
           newman run ./integration_test/config_service/Discovery_Config_Service_Automation.postman_collection.json -e ./integration_test/config_service/Discovery_ENV_Staging.postman_environment.json -r cli,htmlextra